#
### Manifest create Deployment with AutoScaling
#

apiVersion : apps/v1
kind: Deployment

metadata:
  name: flatris-deployment-autoscaling
  labels:
    app: flatris-apps
    owner: KirillDemtchenko

spec:
  selector:
    matchLabels:
      project: skillbox-devops
  template:
    metadata:
      labels:
          project: skillbox-devops
    spec:
      containers:
        - name: flatris
          image: registry.gitlab.com/denav/skillbox
          ports:
            - containerPort: 3000

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler

metadata:
  name: flatris-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: flatris-deployment-autoscaling
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80

---
apiVersion: v1
kind: Service

metadata:
  name: flatris-service
  labels:
     env  : test
     owner: DenisAbarinov
spec:
  selector:
    project: skillbox-devops
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 3000  # Port on Load Balancer
      targetPort: 3000  # Port on Pod
  type: LoadBalancer
